name: Send Scheduled Reminder

on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  build:
    name: Send challenge reminder to groups
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl -X POST -d {} https://daily-habit-bot.deno.dev/remind